### ISSUE TITLE
is it possible to make it compatible to vim plugin?

### ISSUE THREAD

**Issue by drunkenQCat** [sgryjp/japanese-word-handler#25]
especially in visual mode. if so, moving cursor when selecting words will be much more handy.

**Comment by sgryjp** [comment]
Hi, thank you for request!

Could you describe more what do you mean by the word "compatible"? Also an example workflow would be helpful to understand the problem.

By the way, I presume you are mentioning about [Vim extension](https://github.com/VSCodeVim/Vim). In that case the extension also provides word separation logic by its own (derived from the original VIM I guess) so I was thinking users of Vim plugin does not need to use mine.

**Comment by drunkenQCat** [comment]
> By the way, I presume you are mentioning about Vim extension.


yes, that's the plugin what i want to say. the plugin provides vim-like editing experience, like “i” for insert mode, which turn the vscode to editing mode as usual; “v” for visual mode, which is the mode for selecting words by cursor. in visual mode, the cursor can be navigated by w(selecting **word** toward, like ctrl+shift+right arrow) and b(word **backward**).your plugin will work in “i” mode when navigating cursor with ctrl + left arrow/ right arrow. but when it comes to selecting words, the vim plugin will jump to visual mode automaticly.


> In that case the extension also provides word separation logic by its own (derived from the original VIM I guess) 

you're right, it is derived from the original VIM. but unfortunately, VIM doesn't support such logic like your plugin, which will make its `w` and `b` navigate cursor obey space and symbol pattern.

so i have such issue to improve editing experience in vim mode. and if that works, it may be possible to immigrate to original VIM or NeoVIM.

thx for reading my minority requirement. maybe that's unreasonable to make a plugin to be “compatible” to another one, but if there is any solution or just ideas to achive it, i will be so happy to hear that.

**Comment by sgryjp** [comment]
@drunkenQCat Thank you for explanation!

> but when it comes to selecting words, the vim plugin will jump to visual mode automaticly.

So what you want to achieve is suppressing to change Vim's mode from INSERT to VISUAL on expanding selection by japanese-word-handler, right? If so, achieving such behavior might be difficult since the "mode" is provided not by VSCode but by Vim extension. Anyway, I want to understand the problem correctly first so please let me confirm.

> it may be possible to immigrate to original VIM or NeoVIM.

Hmm... sounds like are you willing to switch from VSCode to VIM or Neovim in future? If so, I thought resolving the "problem" (if I correctly understand) described above does not help since the operation is not possible in VIM/Neovim AFAIK.

---

By the way, I'm also a long time VIM user so you can omit explanation of VIM's basic topic 😉

**Comment by drunkenQCat** [comment]
> So what you want to achieve is suppressing to change Vim's mode from INSERT to VISUAL on expanding selection by japanese-word-handler, right? If so, achieving such behavior might be difficult since the "mode" is provided not by VSCode but by Vim extension.

I must extend my sincere apologies for any perceived impoliteness in my inquiry. I would like to clarify that I am a Chinese user myself, and I find that <kbd>w</kbd> and <kbd>b</kbd> is totally works in the word separating logic of [japanese-word-handler](https://github.com/sgryjp/japanese-word-handler) when the words is mixed with kanji and katakana/hirakana.

![keystroke in vim mode](https://github.com/sgryjp/japanese-word-handler/assets/39608175/cbc598ee-555c-4192-aa82-737692c798a0)

in fact, I have been using the [cjk-word-handler](https://github.com/SharzyL/cjk-word-handler) which builds upon your plugin and provides enhanced Chinese word separate logic and corresponding operations. However, when using the Vim plugin, the word separate relies on punctuation marks except using original shortcuts like <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>←/→</kbd>, making cursor movement with <kbd>w</kbd> and <kbd>b</kbd> particularly inconvenient.

![chinese keystroke in vim mode](https://github.com/sgryjp/japanese-word-handler/assets/39608175/c0b82319-d7f6-496c-854e-1b32f14a2ee8)

I found your repository as [cjk-word-handler](https://github.com/SharzyL/cjk-word-handler) is a fork of your repository, and considering the infrequent response to issues by the current maintainer of [cjk-word-handler](https://github.com/SharzyL/cjk-word-handler), I thought it would be worthwhile to inquire if you might have a solution or workaround for this. I understand that you may not be directly responsible for the [cjk-word-handler](https://github.com/SharzyL/cjk-word-handler) , and I apologize for any inconvenience.

誠に申し訳ございませんが、お忙しいところをお邪魔いたしまして、大変失礼いたしました。

I realize that you may not have the time to delve into the specifics, and I genuinely appreciate your consideration. If you are unable to provide assistance, no worries at all. I have found [a blog](https://sharzy.in/posts/2020-02-04-cjk-helper/) detailing the approach and process of modifying your plugin ,and I plan to explore the [cjk-word-handler](https://github.com/SharzyL/cjk-word-handler)'s code myself when time permits, in an attempt to address this issue.

Once again, thank you for your time and understanding.

**Comment by sgryjp** [comment]
@drunkenQCat First of all, I'm sorry that somehow I made you feel uncomfortable by my reply. I have never take your action negatively. I appreciate your feedback. Now I realize the "unwanted change of mode" is not what you are talking about, what you want to achieve is to make Vim extension's cursor movements such as `w` "CJK word aware" (please correct me if this understanding is not right). Let me continue based on this understanding.

#### To make VSCodeVim's word segmentation logic Chinese language friendly

I quickly investigated of VSCodeVim's behavior and its source code concluded that the logic executed by `w` (and `b` and so on) is implemented inside VSCodeVim (perhaps [wordRight() function](https://github.com/VSCodeVim/Vim/blob/v1.27.2/src/cmd_line/commandLine.ts#L158)). Since that code does not belong to japanese-word-handler so there seems to be nothing I can do for that problem, other than recommending you to make an issue or start discussion in their repository. Actually, I found an issue [#8769](https://github.com/VSCodeVim/Vim/issues/8769) in their repository. The author closed it but the reason is that he thinks supporting good Chinese word segmentation should be a feature request rather than bug report. I think it is possible that he/she will create a new feature request issue in near future.

#### To the unnatural mode change on expanding selection in INSERT mode

As I have never investigate why it happens so there is nothing I can say for this topic. Because I think this is not the primary problem of yours so I don't dive into issue, at least for now.

**Comment by drunkenQCat** [comment]
@sgryjp Okay, thanks for your Research and reply. Yes, alright, that's what I want. Now I am hopeful for  VSCodeVim plugin will add this feature in future. That will improve my word editing experience.

Besides, on github, I've found some repositories that are trying to achieve the segmentation logic on VIM and NeoVIM based on **jieba**, the chinese sentense segmenting library, though the configuration wasted all of my afternoon lol.

And finally, 

> I'm sorry that somehow I made you feel uncomfortable by my reply. I have never take your action negatively.

You didn't make me uncomfortable. You can just treat that like some kind of East Asian common “不安” emotion when inquring some else elder than me. It's kind of wired and exaggerating after writed in English. Just take it easy.

Anyway, I'm so happy that you can reply and help me.
